### ISSUE TITLE
报错，找不到 ReactWX.js

### ISSUE THREAD

**Issue by shockw4ver** [RubyLouvre/anu#355]
运行 ``mpreact build`` 或 ``mpreact watch`` 的时候，报了如下错误：
```shell
Error: ENOENT: no such file or directory, open '/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/packages/lib/ReactWX.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.asyncReact (/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/packages/utils/index.js:232:16)
    at Object.<anonymous> (/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/packages/index.js:146:7)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
```

* Node version 10.5.0

**Comment by RubyLouvre** [comment]
修复了
