### ISSUE TITLE
使用 class 时报错

### ISSUE THREAD

**Issue by shockw4ver** [RubyLouvre/anu#363]
在 src/model/db/core.js 中编写了如下内容：
```javascript
class DB {
  constructor () {
    this.db = wx.cloud.database()
    this.cmd = db.command
    this.modules = []
  }

  static getInstance () {
    if (!DB.instance) {
      DB.instance = new DB()
    }

    return DB.instance
  }

  registerModule (module) {
    const { name } = module

    this.modules[name] = module

    Object.defineProperty(this, name, {
      get () {
        return this.modules[name]
      },

      set () {
        return console.warn('请使用 registerModule 进行模块的调整')
      }
    })
  }

  create (collection) {
    return this.db.collection(collection)
  }
}

export default DB.getInstance()
```
然后在其他文件中引用该模块时报错：
```shell

/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/packages/miniTransform.js:117
            if (err) throw err;
                     ^

TypeError: /Users/zhangyongchao/Desktop/workspace/anu/packages/cli/the-minimum-town-mp/src/model/db/core.js: Cannot read property 'tokens' of null
    at new Generator (/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/node_modules/babel-generator/lib/index.js:51:22)
    at exports.default (/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/node_modules/babel-generator/lib/index.js:19:13)
    at PluginPass.enter (/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/packages/wxHelpers/classDeclaration.js:11:30)
    at newFn (/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/zhangyongchao/Desktop/workspace/anu/packages/cli/node_modules/babel-traverse/lib/context.js:192:19)
```
查看后一些错误栈涉及的文件后猜想是 ast 构建失败了...
不知道是什么原因

**Comment by RubyLouvre** [comment]
没有问题
