### ISSUE TITLE
throw new TypeError('Invalid Version: ' + version);

### ISSUE THREAD

**Issue by nyrf** [RubyLouvre/anu#366]
直接拉取的最新的master分支，npm link后，输入mpreact 就报这个错，前面没更新时好的
/Users/nyrf/Codes/weapp/nanachi/anu/packages/cli/node_modules/semver/semver.js:305
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 8
    at new SemVer (/Users/nyrf/Codes/weapp/nanachi/anu/packages/cli/node_modules/semver/semver.js:305:11)
    at compare (/Users/nyrf/Codes/weapp/nanachi/anu/packages/cli/node_modules/semver/semver.js:578:39)
    at Function.lt (/Users/nyrf/Codes/weapp/nanachi/anu/packages/cli/node_modules/semver/semver.js:612:10)
    at Object.<anonymous> (/Users/nyrf/Codes/weapp/nanachi/anu/packages/cli/bin/index.js:7:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by RubyLouvre** [comment]
nodejs 8+，越高越好

**Comment by doabit** [comment]
❯ node -v
v8.11.3

**Comment by doabit** [comment]
我也遇到这个问题了，，

**Comment by nyrf** [comment]
@RubyLouvre  node -v
v10.5.0 我用的最新的还是这个错误

**Comment by Sunshine-97** [comment]
> nodejs 8+，越高越

因为项目需要兼容 ie8 找到了这个框架，借个楼问下，有没有和这个框架配合的好的 ui 框架？

**Comment by nyrf** [comment]
我把原来的目录删了，重新clone后好了，

**Comment by RubyLouvre** [comment]
> 我把原来的目录删了，重新clone后好了，
> 
> 顺便问下，mpreact init 项目能不能选择不要模板，每次init后还要删不要的，谢谢

https://rubylouvre.github.io/nanachi/documents/update.html
