### ISSUE TITLE
mpreact watch 报创建文件夹报错

### ISSUE THREAD

**Issue by wangzhipeng404** [RubyLouvre/anu#493]
错误信息如下
```
getReactLibPath ReactWX.js
- 正在分析依赖...
✔ 依赖分析成功
unhandledRejection { Error: /\D:\anu\spider\spider\dist contains invalid WIN32 path characters.
    at Object.mkdirsSync (D:\anu\packages\cli\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:18:22)
    at Object.createFileSync (D:\anu\packages\cli\node_modules\fs-extra\lib\ensure\file.js:40:11)
    at module.exports (D:\anu\packages\cli\packages\generate.js:22:12)
    at utils.on (D:\anu\packages\cli\packages\index.js:52:5)
    at emit (events.js:182:13)
    at EventEmitter.emit (domain.js:442:20)
    at Object.emit (D:\anu\packages\cli\packages\utils\index.js:29:20)
    at Array.queue.push (D:\anu\packages\cli\packages\queue.js:11:11)
    at transform (D:\anu\packages\cli\packages\miniappTransform.js:21:15)
    at D:\anu\packages\cli\packages\index.js:216:17 code: 'EINVAL' }

```
也找不到 nanachi 命令

**Comment by RubyLouvre** [comment]
那可以用mpreact，这么奇怪。。。mac下没有问题

**Comment by wangzhipeng404** [comment]
我排查了一下，问题主要出在\anu\packages\cli\packages\utils\index.js 里面的 updatePath 方法，它会在路径前面加上反斜杠 `Error: /\D:\anu\spider\spider\dist`
我注释掉这段逻辑就能跑起来了
···
 if (resolvedPath[0] != '/') {
      resolvedPath = '/' + resolvedPath;
} 
···

**Comment by wangzhipeng404** [comment]
跑起来之后我发现模板里面的 ReactWX.js 不是最新的，而且生成的页面引入 ReactWX.js 的路径也是有问题的，像下面这样：
`import React from '..\\..\\ReactWX.js';`
感觉windows下路径的转换很有问题

**Comment by RubyLouvre** [comment]
用 mac就什么事都没有了

**Comment by RubyLouvre** [comment]
我让同事改改

**Comment by RubyLouvre** [comment]
我们修一修

**Comment by wangzhipeng404** [comment]
貌似小程序云开发的目录结构跟原来的目录结构有点不一样，可以添加一个云开发的简易模板吗

**Comment by RubyLouvre** [comment]
我们都不知道云开发是长得怎么样，没有相关的权限与appid

**Comment by RubyLouvre** [comment]
已经修复
