### ISSUE TITLE
got "ReferenceError: window is not defined" when importing ReactDOMServer in node.

### ISSUE THREAD

**Issue by jo32** [RubyLouvre/anu#80]
```
var ReactDOMServer = require('anujs/dist/ReactDOMServer');

ReferenceError: window is not defined
    at .../node_modules/anujs/dist/ReactDOMServer.js:197:1
    at .../node_modules/anujs/dist/ReactDOMServer.js:2:82
    at Object.<anonymous> (.../node_modules/anujs/dist/ReactDOMServer.js:5:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

line 197 in ReactDOMServer.js:

```javascript
var pendingRefs = [];
window.pendingRefs = pendingRefs;
```

**Comment by RubyLouvre** [comment]
var pendingRefs = [];
window.pendingRefs = pendingRefs;

这两行现在没有用了
你直接去掉吧
